[package]
name        = "game"
version     = "0.1.0"
edition     = "2021"
default-run = "game"

[lib]
name = "game"
path = "src/lib.rs"

[[bin]]
name = "game"
path = "src/main.rs"

[[bin]]
name = "survivor"
path = "src/bin/survivor.rs"

[dependencies]
engine     = { package = "skeleton-engine", git = "https://github.com/ChunSam/skeleton-engine", rev = "a3369eef3ac632069b434b1ff4b0bbe8b4158466" }
env_logger = { workspace = true }
log        = { workspace = true }
glam     = { workspace = true }
rapier2d = { workspace = true }
rand     = { workspace = true }
serde    = { workspace = true }
ron      = { workspace = true }
